import dotenv from "dotenv";
import axios from "axios";

dotenv.config();

const API_KEY = process.env.OPENSEA_API_KEY;

async function createCollection() {
  console.log("Creating collection...");

  try {
    const response = await axios.post(
      "https://api.opensea.io/v2/collections",
      {
        contract_address: process.env.CONTRACT_ADDRESS,
        chain: "matic",
        name: "Trend NFT",
        description: "Daily trending NFTs generated by AI",
        schema_name: "ERC721",
        royalty recipient: process.env.PRIVATE_KEY ? "0xEaEf7b52382683f685aF19d4c36A504079d828A5" : undefined,
        royalty_percentage: 10
      },
      {
        headers: {
          "Authorization": API_KEY,
          "Content-Type": "application/json",
          "X-API-KEY": API_KEY
        }
      }
    );
    console.log("✅ Collection created!", response.data);
  } catch (error) {
    console.log("Error:", error.response?.data || error.message);
  }
}

createCollection();